<?php

namespace Milo\VendorVersions\Panel;

use Tracy\Helpers;

/**
 * @var  string $panelTitle
 * @var  string|null $lockFile
 * @var  string|null $jsonFile
 * @var  string|null $error
 * @var  array $data
 * @var  callable $esc
 */
?>
<style class="tracy-debug">
	.milo-VendorVersionsPanel h2 {
		font-weight: bold !important;
	}

	.milo-VendorVersionsPanel small {
		font-size: 85% !important;
	}

	.milo-VendorVersionsPanel table {
		white-space: nowrap;
		font: 9pt/1.5 Consolas,monospace !important;
	}

	.milo-VendorVersionsPanel td.version {
		/*color: green !important;*/
		font-weight: bold !important;
	}
</style>

<h1><?= $esc($panelTitle) ?></h1>
<div class="tracy-inner milo-VendorVersionsPanel">
	<?php if ($error): ?>
		<span style="color:red"><?= $esc($error) ?></span>
	<?php else: ?>
		<?php foreach ($data as $title => $packages): ?>
		<h2><?= $esc($title) ?></h2>
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Installed</th>
					<th>Required</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($packages as $name => $p): ?>
					<tr>
						<td><?= $p->url ? ("<a href='" . $esc($p->url) . "' target='_blank' rel='noreferrer'>" . $esc($name) . "</a>") : $esc($name) ?></td>
						<td class="version"><?= $esc($p->installed) ?></td>
						<td><?= $esc($p->required) ?></td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<?php endforeach ?>
		<p><small>Source: <?= Helpers::editorLink($jsonFile) . $esc(' & ') . Helpers::editorLink($lockFile) ?></small></p>
	<?php endif ?>
</div>
